@startuml Plats_prepares
skin rose

|Responsable des ventes|
start
:Demander le catalogue des recettes;

|Système|
:Vérifier les droits d'accès;
:Envoyer les recettes;
:Catalogue des recettes [complet]; <<task>>

|Responsable des ventes|
:Consulter les recettes;
:Créer ordre de préparation;

|Système|
:Création d'un ordre de préparation;
:Changement des droits d'accès;
:Ordre de préparation [Nouveau]; <<task>>

|Responsable des ventes|
repeat
    :Choisir un plat;
    :Ajouter le plats;
repeat while (liste complète?)
:Ordre de préparation [complèter]; <<task>>

|Chef Traiteur|
repeat :Consulter la liste des plats préparé(s);
:Ajouter la liste des ingrédients;
:Ajouter la recette;
if (Commentaire a ajouté ?) then (oui)
    :Ajouter des commentaires;
else (non)
endif
:définir la date de production;

repeat while (liste complète?)

|Système|
:Sauvegarde du fichier;
:Ordre de préparation [Terminer]; <<task>>

|Chef Traiteur|
:Demander au gestionnaire la vérification des stocks;

|Gestionnaire Stock|
repeat :Consulter la liste des plats préparé(s);
:Faire la liste des ingrédients;
:Faire les quantités des ingrédients;
repeat while (liste parcourue?)
:Consulter les stocks;

|Système|
:Calculer les disponibilités;
:Marquer les produits comme "réservé";

|Gestionnaire Stock|
:Créer le fichier "fiche des disponibilités";

|Système|
:Créer le fichier "fiche des disponibilités";
:Changement des droits d'accès;
:Fiche des disponibilités [Nouveau]; <<task>>

|Système|
fork
    |Responsable des ventes|
    :Consulter la fiche des disponibilités;
    :Choisir les dates de ventes;
    :Valider l'ordre de préparation;

fork again
    |Chef Traiteur|
    :Consulter la fiche des disponibilités;
    :Choisir les dates de ventes;
    :Adapter les dates de production;

    |Système|
end fork
:Ordre de préparation [Validé]; <<task>>

|Cuisinier|
split
    :Attente de date de production; <<timeEvent>>
    :Consulter les plats du jour;

split again
    -[hidden]->
    (A)
    :Consulter les plats restant;
end split

repeat :Consulter les plats du jour;

|Système|
:Ordre de préparation [Validé]; <<task>>

|Cuisinier|
:Consulter la liste des ingrédients;

|Système|
:Liste des ingrédients [Validé]; <<task>>

|Cuisinier|
:Préparer les ingrédients;

|Système|
:Mise à jour des stocks;

|Cuisinier|
:Préparer les plats;
:Encoder quantités réellement produites;

|Système|
:Mise à jour de l'ordre de préparation;
:Ordre de préparation [Mis à jour]; <<task>>

:Génération des étiquettes;
:Étiquettes [Nouvelles]; <<task>>

|Cuisinier|
:Imprimer les étiquettes;
:Coller les étiquettes sur les plats;

|Gestionnaire Stock|
:Rangement des plats au frais;

|Cuisinier|
if (Reste t'il des plats a cuisiner ?) then (non)
    stop
else (oui)
    (A)
    detach
endif

@enduml
