@startuml Plats_prepares
skin rose

|Responsable des ventes|
start
:Demander le catalogue des recettes;

|Système|
:Vérifier les droits d'accès;
if (Droits valides ?) then (oui)
    :Envoyer les recettes;
    :Catalogue des recettes [complet]; <<task>>
else (non)
    :Refuser l'accès;
    stop
endif

|Responsable des ventes|
:Consulter les recettes;
:Créer l'ordre de préparation;

|Système|
:Création d'un ordre de préparation;
:Changement des droits d'accès;
:Ordre de préparation [Nouveau]; <<task>>

|Responsable des ventes|
repeat :Choisir un plat;
    :Ajouter le plat;
    |Système|
    :Sauvegarde du fichier;
    :Ordre de préparation [Sauvegardé]; <<task>>
repeat while (Tous les plats ont été ajoutés à l'ordre ?)


|Chef Traiteur|
:Demander l'ordre de préparation;

|Système|
:Vérifier les droits d'accès;
if (Droits valides ?) then (oui)
    :Ordre de préparation [Terminé];
else (non)
    :Refuser l'accès;
    stop
endif

|Chef Traiteur|
repeat :Consulter l'ordre de préparation;
    :Ajouter la liste des ingrédients;
    :Ajouter la recette;
    if (Commentaire à ajouter ?) then (oui)
        :Ajouter des commentaires;
    else (non)
    endif
    :Définir la date de production du plat;
repeat while (liste complète ?)

|Système|
:Sauvegarde du fichier;
:Ordre de préparation [Terminé]; <<task>>

|Chef Traiteur|
:Demander au gestionnaire la vérification des stocks;

|Gestionnaire Stock|
:Demander l'ordre de préparation;

|Système|
:Vérifier les droits d'accès;
if (Droits valides ?) then (oui)
    :Ordre de préparation [Terminé];
else (non)
    :Refuser l'accès;
    stop
endif

|Gestionnaire Stock|
repeat :Consulter l'ordre de préparation;
    :Établir la liste des ingrédients;
    :Déterminer les quantités d'ingrédients;
    |Système|
    :Calculer les disponibilités en fonction des stocks;
    |Gestionnaire Stock|
repeat while (Toutes les recettes parcourues ?)
:Consulter les stocks;

|Système|
:Réserver les marchandises pour la date de production;

|Gestionnaire Stock|
:Compléter la fiche des disponibilités avec les quantités réelles;

|Système|
:Création du fichier "fiche des disponibilités";
:Changement des droits d'accès;
:Fiche des disponibilités [Nouveau]; <<task>>
:Fiche prête;<<sendSignal>>
'message pour signaler qu’ils peuvent commencer la review
|Système|
fork
    |Responsable des ventes|
    :Consulter la fiche des disponibilités;<<trigger>>
    :Choisir les dates de ventes;
    :Adapter les dates de production;
    :Valider l'ordre de préparation;

fork again
    |Chef Traiteur|
    :Consulter la fiche des disponibilités;<<trigger>>
    :Choisir les dates de ventes;
    :Adapter les dates de production;
    :Attribuer les plats aux cuisiniers;
    :Valider l'ordre de préparation;

    |Système|
end fork

:Vérifier les droits d'accès;
if (Droits valides ?) then (oui)
    :Ordre de préparation [Validé];
else (non)
    :Refuser l'accès;
    stop
endif

|Cuisinier|
split
    :Attente de date de production; <<timeEvent>>
split again
    -[hidden]->
    (A)
end split

:Demander la liste les plats restant à faire;

|Système|
:Vérifier les droits d'accès;
if (Droits valides ?) then (oui)
    :Ordre de préparation \n[Attribué au Cuisinier]; <<task>>
else (non)
    :Refuser l'accès;
    stop
endif

|Cuisinier|
:Demander la liste des ingrédients;

|Système|
:Liste des ingrédients [Validée]; <<task>>

|Cuisinier|
:Consulter la liste des ingrédients;
:Aller chercher les ingrédients;

|Gestionnaire Stock|
:Consulter la liste des ingrédients;
:Donne les ingrédients;

|Cuisinier|
:Préparer les ingrédients;

|Cuisinier|
:Préparer les plats;
:Encoder quantités réellement produites;
if (Remarque à ajouter ?) then (oui)
    :Ajouter remarque;
else (non)
endif

|Système|
:Mise à jour des stocks avec les quantités réellement utilisées;
:Mise à jour de l'ordre de préparation;
:Ordre de préparation [Mis à jour]; <<task>>

:Génération des étiquettes \navec DLC, prix, ingrédients;
:Étiquettes [Nouvelles]; <<task>>

|Cuisinier|
:Imprimer les étiquettes;
:Poser les étiquettes sur les plats;<<sendSignal>>

|Gestionnaire Stock|
:Rangement des plats au frais;<<trigger>>

|Cuisinier|
if (Reste-t-il des plats à cuisiner ?) then (non)
    stop
else (oui)
    (A)
    detach
endif

@enduml