@startuml
|Système de payement|
|Système|
start

split
:Affichage du catalogue des produits disponibles;
:Création du panier;
:Panier [Nouveau]; <<task>>
split again
-[hidden]->
(A)
end split

|Client|
:Ajouter articles;

|Système|
:Panier [Modifié]; <<task>>

|Client|
if (Le client a-t-il fini ?) then (Oui)

    :Confirmation du panier;
    |Système|
    :Panier [Complet] ; <<task>>
    :Appel du service de payement en ligne; <<output>>

    |Système de payement|
    :Réception de l'appel au service; <<input>>
    :Ouverture de la page de payement;
    |Client|
    :Insertion de ses informations de banque;
    :Envoie d'un signal de confirmation du payement; <<output>>

    |Système|
    :Réception du signal de confirmation; <<input>>
    while (Payement accepté ?) is (Non)
        |Client|
        if (Le client veut réessayer le payement ?) then (Non)
            :Panier [Suppression]; <<task>>
            stop
        else (Oui)
            :Reéffectue le payement;

        endif
    end while (Oui)

    |Système|
    :Création d'une facture;
    : Facture \n[Nouveau]; <<task>>

    :Transformation de ce panier en bon de commande;
    :Bon de commande [Nouveau]; <<task>>
    :Envoi du bon de commande; <<output>>

    |Magasinier|
    :1 jour ouvrable avant la date de livraison; <<timeEvent>>
    :Reçu du bon de commande; <<input>>

    :Préparation de la commande;
    :Enregistrement du bon préparé;

    |Système|
    :Bon de commande [Préparée]; <<task>>
    :Diminution du stock par rapport au bon de commande;
    :Stock [Diminués]; <<task>>

    :Création d'un bon de livraison;
    :Bon de livraison [Nouveau]; <<task>>

    |Magasinier|
    :Prévenir le service de livraison;
    :Envoi d'une notification; <<output>>

    |Service de livraison|
    :Réception de la notification; <<input>>
    :S'occupe de la livraison;

    |Client|
    :Reçoit ses courses;
    :Signe le bon de livraison;

    |Service de livraison|
    :Notifie le système du magasin que le client a signé le bon de livraison;

    |Système|
    :Bon de livraison [Signé]; <<task>>

else (Non)
    |Client|
    (A)
    detach
endif

stop


@enduml
