@startuml

state "Ordre de préparations" as carteOrdre {
    state "Nouveau" as carteNew
    state "Incomplet" as carteNotFull
    state "Complet" as carteFull
    state "Dates adaptés" as carteDates
    state "Quantités réelles" as carteQuant : ajouter une remarque

    state cAdaptation <<choice>>

    [*] -> carteNew

    carteNew -> carteNotFull : Choix des plats à préparer

    carteNotFull -> carteFull : Complétion des infos manquantes

    carteFull --> cAdaptation

    cAdaptation --> carteDates : Pas assez de stocks / Dates modifiées
    cAdaptation --> carteQuant : Encodage des quantités réelles produites

    carteDates -> carteQuant : Encodage des quantités réelles produites

}

@enduml
