@startuml "Reapprovisionnement automatique"

skin rose
/'skinparam sequenceMessageAlign center'/

box "Magasin physique" #LightGreen
actor "Comptable" as comptable
actor "Gestionnaire de stock" as gestionnaire
end box

box "Site internet" #LightBlue
entity "Système Magasin" as systeme
database "Base de donnees" as bdd
entity "Serveur mail" as mail
end box

actor "Fournisseur" as fournisseur

/' Verification des stocks '/
activate systeme
systeme ->> systeme : verification_automatique_stock()

systeme -> bdd : lire_niveaux_stock()

activate bdd
bdd --> systeme : liste_produits_et_quantites
deactivate bdd

systeme -> systeme : analyser_seuil_stock()
systeme -> bdd : recuperer_promotions(date)
activate bdd
bdd --> systeme : promotions_courantes
deactivate bdd
systeme -> systeme : croiser_stock_et_promotions()

alt stock < seuil OU promotion_active
    activate gestionnaire
    systeme -> gestionnaire : notification_produits_à_commander()
    gestionnaire --> systeme : consultation notification

    alt commande validee
        gestionnaire ->> systeme : valider_commande()

        systeme -> systeme : generer_bon_commande()
        activate mail
        systeme -> mail : transmettre_bon_commande(liste_produits)
        activate fournisseur
        mail ->> fournisseur : transmettre_commande(liste_produits)
        mail -->> systeme :  confirmation_envoi
        fournisseur -> fournisseur : verifier_disponibilite(liste_produits)

        alt produits disponibles
            fournisseur --> mail : confirmation_commande
            mail -->> systeme : confirmation_commande
            deactivate mail
            systeme -->> gestionnaire : confirmation_commande
            deactivate gestionnaire
            deactivate systeme

            fournisseur -> fournisseur : preparer_commande(liste_produits)
            fournisseur ->> gestionnaire : livrer_commande(id)
            activate gestionnaire

            gestionnaire -> gestionnaire : receptionner_commande()
            gestionnaire -->> fournisseur : confirmer_réception
            fournisseur -> fournisseur : creer_bon_livraison()
            fournisseur -> gestionnaire : demander_signature_bon()
            gestionnaire --> fournisseur : bon signé
            gestionnaire -> systeme : encoder_commande(liste_produits)
            activate systeme
            systeme -> bdd : mettre_a_jour_stock(liste_produits)

            activate bdd
            bdd --> systeme : mettre_à_jour_stock
            deactivate bdd
            systeme --> gestionnaire : confirmation_mise_à_jour
            deactivate systeme

            deactivate gestionnaire

            /'Facturation'/
            fournisseur ->> comptable : envoyer_facture()

            activate comptable
            comptable -> systeme : enregistrer_facture()
            activate systeme
            systeme -> bdd : enregistrer_facture()
            activate bdd
            bdd -> systeme : confirmation_enregistrement
            systeme --> comptable : confirmation_enregistrement
            deactivate bdd
            deactivate systeme

            comptable -->> fournisseur : facture_reçue
            comptable -> fournisseur : effectuer_paiement()
            fournisseur --> comptable : confirmer paiement
            deactivate comptable

        else produits indisponibles
            fournisseur --> mail : indisponibilité_produits
            deactivate fournisseur
            activate mail
            activate systeme
            mail --> systeme : indisponibilité_produits
            deactivate mail
            activate gestionnaire
            systeme --> gestionnaire : notification_indisponibilité
        end
    else commande refusee
        gestionnaire -> systeme : refuser_commande()
        systeme --> gestionnaire : confirmation_refus
        deactivate gestionnaire
        deactivate systeme
    end
end

@enduml