@startuml

 state "Nouveau" as carteNew
    state "Incomplet" as carteNotFull
    state "Complet" as carteFull
    state "Date ajustée" as carteDates
    state "Annulé" as carteCancel
    state "Quantités réelles ajustées" as carteQuant : exit/ ajouter une remarque

    state cAdaptation <<choice>>

    [*] -> carteNew
    carteNew -> carteNotFull : Choix des plats à préparer \n plusieurs semaines à l'avance
    carteNotFull -> carteFull : Complétion de l'ordre de préparations

    carteFull -down-> cAdaptation : Vérification du stock
    cAdaptation -> carteDates : [Stock insuffisant] / Ajustement de la date
    carteDates -left> carteFull : fein

    cAdaptation --> carteCancel : [Stock insuffisant AND date inajustable] / Annulation de l'ordre de préparations
    carteCancel -> [*] : Suppression de l'ordre de préparations

    cAdaptation -left-> carteQuant : [Stock suffisant] / \nAjustement des quantités produites

    carteQuant -left-> [*]

@enduml