@startuml
skin rose
state choice <<choice>>

state "Nouveau" as nouv
nouv: entry/completer les informations
nouv: exit/assigner la carte à un compte client

state "Associé" as asso
asso: entry/associer la carte à un ticket

state "Point ajouté" as ptajout
ptajout: entry/ajouter les points à la carte

state "Point retiré" as ptret
ptret: entry/retirer les points à la carte
ptret: exit/appliquer  la réduction

state "Cloturé" as clot
clot: entry/cloturer la carte
clot: exit/cloturer le compte

[*] -right-> nouv :création de la carte
nouv --> asso :création d'un ticket

asso ---> choice :demande au client si utilisation des points
choice --> ptret :[nombre de points suffisant et utilisation points]
choice --> ptajout :[else]
ptret ---> ptajout :validation payement ticket

ptajout --> asso :création d'un nouveau ticket
ptajout --> clot :demande de suppression du compte
clot --> [*]
@enduml
