@startuml
skin rose
skinparam usecase {
  BackgroundColor #FEFEFE
  BorderColor #999999
  ArrowColor #666666
  ActorBorderColor #555555
}
skinparam rectangle {
  BorderColor #888888
  BackgroundColor #FFFFF0
}

left to right direction


actor "Responsable des ventes"  as RV
actor "Chef Traiteur"           as CT
actor "Gestionnaire de stocks"  as GS
actor "Cuisinier"               as CU


rectangle Front_end {
  (Planifier les plats) as PP
  (Consulter les commandes) as CC
  (Compléter les commandes) as CC2
  (Réserver les marchandises) as RM
  (Distribuer recettes) as DR
  (Imprimer étiquettes) as IE
  (Modifier les dates) as MD
  RV --> PP
  RV --> CC
  CT --> CC
  CT --> DR
  GS --> RM
  DR --> CU
  CU --> CC
  CT --> IE
  CT --> MD
}

rectangle back_end {
  (Encoder les plats) as EP
  (Consulter les préparations) as CP
  (Compléter les préparations) as CP2
  (Réserver les marchandises) as RM2
  (Vérifier disponibilité des stocks) as VDS
  (Modifier les dates) as MD2
  (Ajouter remarques) as AR
  PP --> EP
  CC --> CP
  CC2 --> CP2
  RM --> RM2
  RM2 ..> VDS : include
  CP ..> VDS : include
  CP2 ..> AR : extend
  IE ..> VDS : extend
  MD ..> MD2 : extend
}

rectangle BD {
  (Ajouter) as A
  (Modifier) as M
  (Supprimer) as S
  (Consulter) as C
  EP ..> A : include
  CP ..> C : include
  CP2 ..> M : include
  VDS ..> C : include
  MD2 ..> M : include
}

@enduml