@startwbs
skin rose 

* Project "Magasin du Grand Bazard"
** Initiation
*** Identifier les besoins du client
*** Définition des objectifs avec le client
** Planning
*** Work breakdown structure
*** Analyse
**** Besoin
**** Orienté Objet
**** UX
**** Définition et contremesure pour les risques
*** Agenda
*** Définition de l'équipe de développement
*** Budgetisation
** Execution
*** Development
*** Testing
*** Documentation 
** Closure
*** Installation chez le client
*** Acceptance 
*** Post mortem 
*** Phase de transition 
*** Retour 
@endwbs
