@startwbs
skin rose 

* Project "Magasin du Grand Bazard"
** Initiation
*** Identifier les besoins du client
*** Définition des objectifs avec le client
** Planning
*** Définition de la gestion du projet
**** Work breakdown structure
**** Diagramme de gantt 
**** Matrice RACI pour la gestion du projet
**** Matrice de FARMER pour la gestion du projet 
*** Analyse
**** Besoin
**** Orienté Objet
**** UX
**** Définition et contremesure pour les risques
*** Agenda
*** Définition de l'équipe de développement
*** Budgetisation
** Execution
*** Development
*** Testing
*** Documentation 
** Closure
*** Installation chez le client
*** Acceptance 
*** Post mortem 
*** Phase de transition 

@endwbs
